namespace Syntera.Backend.Models.Dtos.Auth;

public record LoginRequest(string Email, string Password);

/// <summary>
/// Login response. Fields <see cref="RequiresMfa"/>, <see cref="MfaChallengeToken"/>,
/// <see cref="RequiresPasswordChange"/>, and <see cref="PasswordChangeChallengeToken"/>
/// are NEW (Sprint 2.3) and default to <c>false</c>/<c>null</c> for backward compat —
/// pre-MFA clients continue to read <see cref="AccessToken"/>/<see cref="RefreshToken"/>
/// exactly as before. When a challenge is required, <see cref="AccessToken"/> and
/// <see cref="RefreshToken"/> are returned empty and the client MUST follow the
/// challenge field instead of attempting to use the access token.
/// </summary>
public record LoginResponse(
    string AccessToken,
    DateTime ExpiresAt,
    string RefreshToken,
    UserProfileDto Profile,
    ThemeDto Theme,
    bool RequiresMfa = false,
    string? MfaChallengeToken = null,
    bool RequiresPasswordChange = false,
    string? PasswordChangeChallengeToken = null);

/// <summary>
/// F5-LOGOUT FIX (2026-09-09): RefreshToken is deliberately NULLABLE.
/// With the cookie-only transport (H7) the browser client posts an EMPTY
/// body ("{}") — the token arrives via the httpOnly `syntera_refresh`
/// cookie, never in the body. A non-nullable parameter is treated by MVC
/// as implicitly [Required], so the [ApiController] auto-validation filter
/// returned 400 VALIDATION_FAILED ("The RefreshToken field is required.")
/// BEFORE the action method executed — the cookie was never read and every
/// silent refresh (app boot / F5 / 401 interceptor) logged the user out.
/// The controller treats a null body token as "use the cookie" and returns
/// EMPTY_TOKEN only when BOTH cookie and body are absent.
/// </summary>
public record RefreshRequest(string? RefreshToken = null);

public record RefreshResponse(
    string AccessToken,
    DateTime ExpiresAt,
    string RefreshToken,
    UserProfileDto Profile,
    ThemeDto Theme);

public record UserProfileDto(
    Guid UserId,
    string Email,
    string DisplayName,
    string? Title,
    string Scope,        // "platform" | "site"
    Guid? SiteId,
    string? SiteCode,
    string? SiteDisplayName,
    IReadOnlyCollection<string> Roles,
    IReadOnlyCollection<string> Permissions);

public record ThemeDto(
    string ThemeKey,
    ThemePalette Light,
    ThemePalette Dark,
    string? LogoUrl);

public record ThemePalette(
    string Primary,
    string Accent,
    string Background,
    string Surface,
    string Text,
    string Muted,
    string Border,
    string Success,
    string Warning,
    string Danger);

/// <summary>
/// F5-LOGOUT FIX (2026-09-09): same reasoning as <see cref="RefreshRequest"/>
/// — the cookie-only frontend posts an empty body ("{}") to /api/auth/logout
/// and relies on the httpOnly cookie; a non-nullable (implicitly required)
/// parameter made the request die in model validation before the action ran,
/// so the server-side revoke never happened.
/// </summary>
public record LogoutRequest(string? RefreshToken = null);

// ── COMPLIANCE (Sprint 2.3): MFA + password max-age DTOs ──────────────────

/// <summary>
/// COMPLIANCE (Sprint 2.3): Body for POST /api/auth/login-mfa. Completes the
/// login flow after the user provided a valid password but the platform admin
/// had MFA (TOTP) enabled. The <see cref="MfaChallengeToken"/> is the short-lived
/// JWT returned by the initial POST /api/auth/login response
/// (see <see cref="LoginResponse.MfaChallengeToken"/>); <see cref="Code"/> is
/// the 6-digit TOTP code from the user's authenticator app.
/// </summary>
public sealed record LoginMfaRequest(string MfaChallengeToken, string Code);

/// <summary>
/// COMPLIANCE (Sprint 2.3): Body for POST /api/auth/mfa/setup. Returned to the
/// caller so the frontend can render a QR code (from <see cref="QrCodeUrl"/>) and
/// show the manual-entry secret (<see cref="PlaintextSecret"/>) for users without
/// a phone camera. The secret is NOT yet enabled — the user must call
/// POST /api/auth/mfa/confirm with a valid TOTP code first.
/// </summary>
public sealed record MfaSetupResponse(string QrCodeUrl, string PlaintextSecret);

/// <summary>
/// COMPLIANCE (Sprint 2.3): Body for POST /api/auth/mfa/confirm. Verifies the
/// first TOTP code generated by the user's authenticator app against the
/// just-stored (but not yet enabled) TOTP secret, and enables MFA for the
/// caller's account on success.
/// </summary>
public sealed record ConfirmMfaRequest(string Code);

/// <summary>
/// COMPLIANCE (Sprint 2.3): Body for POST /api/auth/mfa/disable. The user
/// must provide a current valid TOTP code as confirmation — this prevents
/// accidental (or attacker-initiated) MFA disable without possession of the
/// authenticator device.
/// </summary>
public sealed record DisableMfaRequest(string Code);

/// <summary>
/// COMPLIANCE (Sprint 2.3): Body for POST /api/auth/change-password. The
/// <see cref="CurrentPassword"/> is required for voluntary self-service
/// password changes. The optional <see cref="PasswordChangeChallengeToken"/>
/// is used by the FORCED password change flow (login returned
/// <see cref="LoginResponse.RequiresPasswordChange"/> = true): when
/// present, the server accepts the change without verifying the current
/// password (the challenge token already proves identity via JWT signature).
/// At least one of the two must be present.
/// </summary>
public sealed record ChangePasswordRequest(
    string CurrentPassword,
    string NewPassword,
    string? PasswordChangeChallengeToken = null);
